### ISSUE TITLE
Rename init parameter

### ISSUE THREAD

**Issue by forki** [thoth-org/Thoth.Fetch#1]
![image](https://user-images.githubusercontent.com/57396/57836009-19b18000-77c0-11e9-8d42-65718a28f2bf.png)

maybe call it `props`?

**Comment by MangelMaxime** [comment]
Oh yes, good catch.
I forget to rename it everywhere after deciding to name it `properties`.

[Source](https://github.com/thoth-org/Thoth.Fetch/blob/master/src/Fetch.fs#L161)

**Comment by MangelMaxime** [comment]
PS: Seems like we have a bug in Ionide, it shows twice `Description` in the tooltip.
