### ISSUE TITLE
Blocking JS import on the documentation page

### ISSUE THREAD

**Issue by joahim** [thoth-org/Thoth.Fetch#47]
Access to the documentation page https://thoth-org.github.io/Thoth.Fetch/ usually takes a long time (1/2 min) due to the blocking JS import from https://polyfill.app/api/polyfill?features=scroll-behavior. When the connection for this resource times out the page renders without problems.

**Comment by MangelMaxime** [comment]
Thank you for the report.

I upgraded to the latest version of Nacara which should fix the problem.
